Repository RcDevRIL/cesi_covid_19_tracker, pull requests merged in 2020-05, with the labels that each got.

#57 Update Readme.md
  README.md
  lib/ui/pages/country_view.dart
Labels: documentation

#56 Added English README (fix #52)
  README-en.md
Labels: documentation

#58 Dev readme fix #52
  README-en.md
  README.md
Labels: documentation

#59 Implement simple way of getting a full list of countries
  assets/data/data_csv.csv
  lib/data/services/app_utils/app_utils.dart
  lib/data/services/app_utils/app_utils_impl.dart
  lib/ui/pages/country_view.dart
  pubspec.yaml
Labels: backend, enhancement

#64 Dev country view
  README-en.md
  README.md
  assets/data/data_csv.txt
  lib/data/constants/app_globals.dart
  lib/data/models/country.dart
  lib/data/models/country.freezed.dart
  lib/data/models/country.g.dart
  lib/data/models/covid_country_infos.dart
  lib/data/models/covid_infos.dart
  lib/data/models/models.dart
  lib/data/services/api_service/api_service.dart
  lib/data/services/api_service/api_service_impl.dart
  lib/data/services/app_utils/app_utils.dart
  lib/data/services/app_utils/app_utils_impl.dart
  lib/data/services/locator.dart
  lib/data/services/provider/coroned_data.dart
  lib/data/services/services.dart
  lib/main.dart
  lib/ui/pages/country_view.dart
  lib/ui/pages/covid_faq.dart
  lib/ui/pages/dashboard.dart
  lib/ui/pages/details_page.dart
  lib/ui/pages/pages.dart
  lib/ui/widgets/cards/coroned_card.dart
  lib/ui/widgets/cards/country_card.dart
  lib/ui/widgets/cards/global_card.dart
  lib/ui/widgets/coroned_country_card.dart
  lib/ui/widgets/coroned_global_card.dart
  lib/ui/widgets/navbar_item.dart
  lib/ui/widgets/navigation_drawer/navigation_drawer.dart
  lib/ui/widgets/navigation_drawer/navigation_drawer_header.dart
  lib/ui/widgets/widgets.dart
  pubspec.yaml
  test/unit_test.dart
Labels: UI/UX, backend, bug, enhancement

#67 v1.3-RELEASE
  README-en.md
  README.md
  lib/data/constants/app_globals.dart
  lib/data/models/country.dart
  lib/data/models/country.freezed.dart
  lib/data/models/country.g.dart
  lib/data/models/covid_country_infos.dart
  lib/data/models/covid_infos.dart
  lib/data/models/models.dart
  lib/data/services/api_service/api_service.dart
  lib/data/services/api_service/api_service_impl.dart
  lib/data/services/app_utils/app_utils.dart
  lib/data/services/app_utils/app_utils_impl.dart
  lib/data/services/locator.dart
  lib/data/services/provider/coroned_data.dart
  lib/data/services/services.dart
  lib/main.dart
  lib/ui/pages/country_view.dart
  lib/ui/pages/covid_faq.dart
  lib/ui/pages/dashboard.dart
  lib/ui/pages/details_page.dart
  lib/ui/pages/pages.dart
  lib/ui/widgets/cards/coroned_card.dart
  lib/ui/widgets/cards/country_card.dart
  lib/ui/widgets/cards/global_card.dart
  lib/ui/widgets/coroned_country_card.dart
  lib/ui/widgets/coroned_global_card.dart
  lib/ui/widgets/navbar_item.dart
  lib/ui/widgets/navigation_drawer/navigation_drawer.dart
  lib/ui/widgets/navigation_drawer/navigation_drawer_header.dart
  lib/ui/widgets/widgets.dart
  pubspec.yaml
  test/unit_test.dart
Labels: enhancement

#74 v1.4
  assets/missing_flag.png
  lib/data/constants/app_globals.dart
  lib/data/services/api_service/api_service_impl.dart
  lib/data/services/app_utils/app_utils.dart
  lib/data/services/app_utils/app_utils_impl.dart
  lib/data/services/exceptions/covid_not_found.dart
  lib/data/services/exceptions/exceptions.dart
  lib/data/services/provider/coroned_data.dart
  lib/main.dart
  lib/ui/pages/country_view.dart
  lib/ui/pages/covid_faq.dart
  lib/ui/pages/dashboard.dart
  lib/ui/pages/details_page.dart
  lib/ui/widgets/cards/cards.dart
  lib/ui/widgets/cards/failure_card.dart
  lib/ui/widgets/coroned_app_bar.dart
  lib/ui/widgets/failure_icon.dart
  lib/ui/widgets/navbar_item.dart
  lib/ui/widgets/navigation_drawer/navigation_drawer.dart
  lib/ui/widgets/navigation_drawer/navigation_drawer_header.dart
  lib/ui/widgets/widgets.dart
  pubspec.yaml
Labels: enhancement
