Repository RcDevRIL/cesi_covid_19_tracker, pull requests merged in 2020-04, with the labels that each got.

#21 Migrate API
  lib/data/models/covid_latest.dart
  lib/data/models/covid_latest.freezed.dart
  lib/data/models/covid_latest.g.dart
  lib/data/services/app_utils/app_utils.dart
  lib/data/services/app_utils/app_utils_impl.dart
  lib/data/services/locator.dart
  lib/data/services/services.dart
  lib/ui/pages/dashboard.dart
  lib/ui/pages/home_page.dart
Labels: enhancement, good first issue

#23 Updated README sections + Changed App Name
  README.md
  lib/main.dart
Labels: documentation

#27 added logo for app
  assets/virus-logo.png
  web/favicon.png
  web/icons/Icon-192.png
  web/icons/Icon-512.png
  web/icons/android-icon-144x144.png
  web/icons/android-icon-192x192.png
  web/icons/android-icon-36x36.png
  web/icons/android-icon-48x48.png
  web/icons/android-icon-72x72.png
  web/icons/android-icon-96x96.png
  web/icons/apple-icon-114x114.png
  web/icons/apple-icon-120x120.png
  web/icons/apple-icon-144x144.png
  web/icons/apple-icon-152x152.png
  web/icons/apple-icon-180x180.png
  web/icons/apple-icon-57x57.png
  web/icons/apple-icon-60x60.png
  web/icons/apple-icon-72x72.png
  web/icons/apple-icon-76x76.png
  web/icons/apple-icon-precomposed.png
  web/icons/apple-icon.png
  web/icons/browserconfig.xml
  web/icons/favicon-16x16.png
  web/icons/favicon-32x32.png
  web/icons/favicon-96x96.png
  web/icons/ms-icon-144x144.png
  web/icons/ms-icon-150x150.png
  web/icons/ms-icon-310x310.png
  web/icons/ms-icon-70x70.png
  web/index.html
  web/manifest.json
Labels: enhancement, good first issue

#28 Implementation tests - added basic implementation tests
  pubspec.yaml
  test_driver/coroned_app.dart
  test_driver/coroned_app_test.dart
Labels: enhancement, good first issue

#29 refactor unit test and add test on api service call
  .gitignore
  lib/data/services/app_utils/app_utils_impl.dart
  test/unit_test.dart
  test/unit_tests_constants.dart
  test/widget_test.dart
Labels: enhancement, good first issue

#33 fix issue with DTO CovidInfos and implement some responsiveness for Card
  lib/data/models/covid_infos.dart
  lib/data/models/covid_infos.freezed.dart
  lib/data/models/covid_infos.g.dart
  lib/ui/pages/country_view.dart
  lib/ui/widgets/coroned_country_card.dart
  lib/ui/widgets/coroned_global_card.dart
  lib/ui/widgets/navbar_item/navbar_item_desktop.dart
Labels: enhancement

#36 Devstatbar
  lib/ui/pages/country_view.dart
  lib/ui/pages/dashboard.dart
  lib/ui/widgets/coroned_country_card.dart
  lib/ui/widgets/coroned_global_card.dart
Labels: enhancement

#37 [Fixes] Dropdown text color and number formatting
  lib/data/services/app_utils/app_utils.dart
  lib/data/services/app_utils/app_utils_impl.dart
  lib/data/services/services.dart
  lib/ui/pages/country_view.dart
  lib/ui/widgets/coroned_country_card.dart
  lib/ui/widgets/coroned_global_card.dart
  pubspec.yaml
Labels: enhancement

#39 cesi_covid_19_tracker v0.3 RELEASE
  lib/data/models/covid_infos.dart
  lib/data/models/covid_infos.freezed.dart
  lib/data/models/covid_infos.g.dart
  lib/data/services/app_utils/app_utils.dart
  lib/data/services/app_utils/app_utils_impl.dart
  lib/data/services/services.dart
  lib/ui/pages/country_view.dart
  lib/ui/pages/dashboard.dart
  lib/ui/widgets/coroned_country_card.dart
  lib/ui/widgets/coroned_global_card.dart
  lib/ui/widgets/navbar_item/navbar_item_desktop.dart
  pubspec.yaml
Labels: enhancement

#43 fix #42
  lib/data/services/app_utils/app_utils_impl.dart
Labels: bug, enhancement

#44 fix #40
  lib/ui/widgets/coroned_country_card.dart
  lib/ui/widgets/coroned_global_card.dart
Labels: bug, enhancement

#45 cesi_covid_19_tracker v1.0 RELEASE
  assets/FR_virus.png
  assets/UK_virus.png
  assets/US_virus.png
  assets/cesilogo.png
  lib/data/constants/app_globals.dart
  lib/data/models/models.dart
  lib/data/services/app_utils/app_utils_impl.dart
  lib/data/services/locator.dart
  lib/main.dart
  lib/ui/pages/country_view.dart
  lib/ui/pages/covid_faq.dart
  lib/ui/pages/dashboard.dart
  lib/ui/pages/pages.dart
  lib/ui/widgets/coroned_country_card.dart
  lib/ui/widgets/coroned_global_card.dart
  lib/ui/widgets/navbar_item.dart
  lib/ui/widgets/navbar_item/navbar_item_desktop.dart
  lib/ui/widgets/navbar_item/navbar_item_mobile.dart
  lib/ui/widgets/navigation_drawer/navigation_drawer.dart
  lib/ui/widgets/widgets.dart
  pubspec.yaml
Labels: documentation, enhancement, help wanted

#49 remove unused images + fix API call (now hit v2 endpoints)
  assets/FR_virus.png
  assets/UK_virus.png
  assets/US_virus.png
  assets/virus.jpg
  lib/data/services/app_utils/app_utils_impl.dart
  lib/ui/pages/country_view.dart
  pubspec.yaml
Labels: bug, enhancement

#51 Dev v1.2
  assets/FR_virus.png
  assets/UK_virus.png
  assets/US_virus.png
  assets/virus.jpg
  lib/data/services/app_utils/app_utils_impl.dart
  lib/ui/pages/country_view.dart
  pubspec.yaml
Labels: enhancement
